-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 13:02:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `PersonID` INT NOT NULL,
  `FName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `PreferredContact` VARCHAR(45) NOT NULL,
  `StreetName1` VARCHAR(45) NOT NULL,
  `ApartmentNumber` VARCHAR(45) NOT NULL,
  `Zipcode` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PersonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `PersonID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `NumberOfPets` INT NOT NULL,
  `JoinDate` DATE NOT NULL,
  PRIMARY KEY (`PersonID`),
  CONSTRAINT `fk_Clients_Person1`
    FOREIGN KEY (`PersonID`)
    REFERENCES `mydb`.`Person` (`PersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pets` (
  `PetID` INT NOT NULL,
  `ClientID` INT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PetID`),
  INDEX `fk_Pets_Clients1_idx` (`ClientID` ASC),
  CONSTRAINT `fk_Pets_Clients1`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Clients` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `PersonID` INT NOT NULL,
  `TechID` VARCHAR(45) NOT NULL,
  `SSN` VARCHAR(9) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Certification` TINYINT NOT NULL,
  `Available` VARCHAR(45) NOT NULL,
  `Hire_Date` DATE NOT NULL,
  `Rating` INT,
  PRIMARY KEY (`PersonID`),
  CONSTRAINT `fk_Technician_Person1`
    FOREIGN KEY (`PersonID`)
    REFERENCES `mydb`.`Person` (`PersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `ServiceID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Cost` FLOAT NOT NULL,
  PRIMARY KEY (`ServiceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discounts` (
  `DiscountID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Discount` FLOAT NOT NULL,
  `ClientID` INT NOT NULL,
  PRIMARY KEY (`DiscountID`),
  INDEX `fk_Discounts_Clients1_idx` (`ClientID` ASC),
  CONSTRAINT `fk_Discounts_Clients1`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Clients` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentDiscount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentDiscount` (
  `DiscountID` INT NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  `GraduationDate` DATE NOT NULL,
  `SchoolName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DiscountID`),
  CONSTRAINT `fk_StudentDiscount_Discounts1`
    FOREIGN KEY (`DiscountID`)
    REFERENCES `mydb`.`Discounts` (`DiscountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TeacherDiscount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TeacherDiscount` (
  `DiscountID` INT NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `SchoolName` VARCHAR(45) NOT NULL,
  `Coach` TINYINT NOT NULL,
  PRIMARY KEY (`DiscountID`),
  CONSTRAINT `fk_TeacherDiscount_Discounts1`
    FOREIGN KEY (`DiscountID`)
    REFERENCES `mydb`.`Discounts` (`DiscountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `OrderID` INT NOT NULL,
  `PetID` INT NULL,
  `Start` DATETIME(5) NOT NULL,
  `End` DATETIME(5) NOT NULL,
  `TechID` INT NULL,
  `Subtotal` FLOAT NOT NULL,
  `Total` FLOAT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Orders_Pets1_idx` (`PetID` ASC),
  INDEX `fk_Orders_Technician1_idx` (`TechID` ASC),
  CONSTRAINT `fk_Orders_Pets1`
    FOREIGN KEY (`PetID`)
    REFERENCES `mydb`.`Pets` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Technician1`
    FOREIGN KEY (`TechID`)
    REFERENCES `mydb`.`Technician` (`TechID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SpecialNeeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SpecialNeeds` (
  `NeedsID` INT NOT NULL,
  `PetID` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`NeedsID`),
  INDEX `fk_MedRecords_Pets1_idx` (`PetID` ASC),
  CONSTRAINT `fk_MedRecords_Pets1`
    FOREIGN KEY (`PetID`)
    REFERENCES `mydb`.`Pets` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderServices` (
  `OrderServiceID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `ServiceID` INT NOT NULL,
  PRIMARY KEY (`OrderServiceID`),
  INDEX `fk_OrderServices_Orders1_idx` (`OrderID` ASC),
  INDEX `fk_OrderServices_Services1_idx` (`ServiceID` ASC),
  CONSTRAINT `fk_OrderServices_Orders1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderServices_Services1`
    FOREIGN KEY (`ServiceID`)
    REFERENCES `mydb`.`Services` (`ServiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `RateID` INT NOT NULL,
  `Rating` INT NULL,
  `Rater` VARCHAR(45) NULL,
  `Comment` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `TechID` INT NOT NULL,
  PRIMARY KEY (`RateID`),
  INDEX `fk_Rating_Technician1_idx` (`TechID` ASC),
  CONSTRAINT `fk_Rating_Technician1`
    FOREIGN KEY (`TechID`)
    REFERENCES `mydb`.`Technician` (`TechID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
